configuration-controllers:
    resource:
        path: ../src/Transport/Controller/Api/
        namespace: App\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json
